resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/Viren0602/Vault-task.git
      branch: main

jobs:
  - name: fetch-screener-data
    plan:
      - get: repo
        trigger: true

      - task: fetch-credentials
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: latest

          params:
            VAULT_ADDR: 'http://192.168.3.174:8200'
            VAULT_TOKEN: 'test'

          run:
            path: /bin/sh
            args:
              - -c
              - |
                export VAULT_ADDR='http://192.168.3.174:8200'
                export VAULT_TOKEN='test'

                USERNAME=$(vault kv get -field=username secret/myapp)
                PASSWORD=$(vault kv get -field=password secret/myapp)

                export VAULT_USERNAME=$USERNAME
                export VAULT_PASSWORD=$PASSWORD

                echo "Fetched Username: $VAULT_USERNAME"
                echo "Fetched Password: $VAULT_PASSWORD"

             

      - task: download-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.8

          inputs:
            - name: repo

          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd repo
                pip install --upgrade pip
                pip install requests beautifulsoup4
                python download-data.py

      - task: scrape-and-insert
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mcr.microsoft.com/mssql-tools
              tag: latest

          inputs:
            - name: repo

          run:
            path: /bin/bash
            args:
              - -c
              - |
                apt-get update
                apt-get install -y python3-pip
                pip3 install pandas pyodbc
                cd repo
                python3 scrape_and_insert.py











# resources:
#   - name: repo
#     type: git
#     source:
#       uri: https://github.com/Viren0602/Vault-task.git
#       branch: main

# jobs:
#   - name: fetch-screener-data
#     plan:
#       - get: repo
#         trigger: true

#       - task: fetch-credentials
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: python
#               tag: latest

#           params:
#             VAULT_ADDR: 'http://0.0.0.0:8200'
#             VAULT_USER: 'viren'
#             VAULT_PASS: 'viren@9999'

#           run:
#             path: /bin/sh
#             args:
#               - -c
#               - |
#                 cd repo
#                 ./fetch_credentials.sh
#                 echo "Fetched username: $SCREENER_USERNAME"
#                 echo "Fetched password: $SCREENER_PASSWORD"
# # login-and-download
#       - task: download-data
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: python
#               tag: 3.8

#           inputs:
#             - name: repo

#           run:
#             path: /bin/bash
#             args:
#               - -c
#               - |
#                 cd repo
#                 # ls -l
#                 pip install --upgrade pip
#                 pip install requests
#                 pip install beautifulsoup4  # Ensure BeautifulSoup is installed
#                 python download-data.py

#       - task: scrape-and-insert
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: mcr.microsoft.com/mssql-tools
#               tag: latest

#           inputs:
#             - name: repo

#           run:
#             path: /bin/bash
#             args:
#               - -c
#               - |
#                 apt-get update
#                 apt-get install -y python3-pip
#                 pip3 install pandas pyodbc
#                 cd repo
#                 python3 scrape_and_insert.py















# resources:
#   - name: repo
#     type: git
#     source:
#       uri: https://github.com/Viren0602/Vault-task.git
#       branch: main  # or the correct branch name

# jobs:
#   - name: fetch-screener-data
#     plan:
#       - get: repo
#         trigger: true

#       - task: fetch
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: python
#               tag: latest
#               # hashicorp/vault

#           params:
#             VAULT_ADDR: 'http://0.0.0.0:8200'
#             VAULT_USER: 'viren'
#             VAULT_PASS: 'viren'

#           run:
#             path: /bin/sh
#             args:
#               - -c
#               - |
#                 cd repo
#                 ./fetch.sh
#                 echo "Fetched username: $SCREENER_USERNAME"
#                 echo "Fetched password: $SCREENER_PASSWORD"

#       - task: login-and-download
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: python
#               tag: 3.8

#           inputs:
#             - name: repo

#           run:
#             path: /bin/bash
#             args:
#               - -c
#               - |
#                 cd repo
#                 python download_data.py

#       - task: scrape-and-insert
#         config:
#           platform: linux
#           image_resource:
#             type: docker-image
#             source:
#               repository: mcr.microsoft.com/mssql-tools
#               tag: latest

#           inputs:
#             - name: repo

#           run:
#             path: /bin/bash
#             args:
#               - -c
#               - |
#                 apt-get update
#                 apt-get install -y python3-pip
#                 pip3 install pandas pyodbc
#                 cd repo
#                 python3 scrape_and_insert.py
